### ISSUE TITLE
Crash when opening config

### ISSUE THREAD

**Issue by Rekrii** [Smurf-IV/Elucidate#29]
When I try to open a config file I get the following exception. Running from the CLI seems to work fine.

**Config:**
parity D:\snapraid.parity

content C:\snapraid.content
content D:\snapraid.content

data d1 E:\
data d2 F:\
data d3 G:\

exclude *.unrecoverable
exclude Thumbs.db
exclude \$RECYCLE.BIN
exclude \System Volume Information
exclude \Program Files\
exclude \Program Files (x86)\
exclude \Windows\

**Exception:**
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.Max[TSource](IEnumerable`1 source)
   at Elucidate.ConfigFileHelper.DoValidation()
   at Elucidate.ElucidateForm.LoadConfigFile(String configFile)
   at Elucidate.ElucidateForm.OpenSnapRAIDConfigToolStripMenuItem_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by hidegh** [comment]
@Rekrii possibly relates to: https://github.com/Smurf-IV/Elucidate/issues/12
Use disk keyword instead of data and make it zero based d0..dN, this should make your config readable. Hope this helps.

**Comment by Rekrii** [comment]
@hidegh Thanks, spot on. I seem to have missed that thread. Using the 10.x keyword 'disk' works.
